version: '1.0'


services:
  web:
    build: ./
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docops/:/home/utkarsh/development/docops/ 
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev 
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docops
      - POSTGRES_PASSWORD=docops
      - POSTGRES_DB=docops_db


volumes:
  postgres_data:
