# Generated by Django 4.2.5 on 2023-11-06 08:12

from django.db import migrations, models
import django.db.models.deletion
import files.models.file
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrivate', models.BooleanField(default=False)),
                ('inviteCode', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('docId', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('heading', models.CharField(blank=True, max_length=64, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=files.models.file.get_filename)),
            ],
            options={
                'permissions': [('can_comment', 'Can comment'), ('can_edit', 'Can Edit')],
            },
        ),
        migrations.CreateModel(
            name='FileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
    ]
