# Generated by Django 4.2.5 on 2023-11-06 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file', to_field='docId'),
        ),
    ]
