# Generated by Django 4.2.5 on 2023-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.IntegerField(choices=[(0, 'Request to join space'), (1, 'Request to edit a file')]),
        ),
    ]
